[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：不支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持

ruleset=🎯 全球直连,rules/ACL4SSR/Clash/LocalAreaNetwork.list
ruleset=📢 谷歌FCM,rules/ACL4SSR/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,rules/ACL4SSR/Clash/Microsoft.list
ruleset=📲 电报信息,rules/ACL4SSR/Clash/Telegram.list
ruleset=📱 TikTok,rules/ACL4SSR/Clash/Ruleset/TikTok.list
ruleset=💬 OpenAi,rules/ACL4SSR/Clash/Ruleset/OpenAi.list
ruleset=💬 Gemini,rules/ACL4SSR/Clash/Ruleset/Gemini.list
ruleset=💬 其它Ai,rules/ACL4SSR/Clash/Ruleset/Ai.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/Ruleset/PrivateTracker.list?v=1
ruleset=🌍 国外媒体,rules/ACL4SSR/Clash/ProxyMedia.list
ruleset=🚀 节点选择,rules/ACL4SSR/Clash/ProxyLiteH.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaDomain.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaCompanyIp.list
ruleset=🛑 全球拦截,rules/ACL4SSR/Clash/FuckAdobe.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动智能`[]🚀 SELF节点`[]🇭🇰 香港智能`[]🇹🇼 台湾智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇺🇸 美国智能`[]🇰🇷 韩国智能`[]🇹🇷 土耳其智能`[]🚀 手动切换`[]DIRECT`.*
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动智能`smart`.*`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动智能`[]🎯 全球直连`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇰🇷 韩国智能`[]🇹🇼 台湾智能`[]🇹🇷 土耳其智能`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇰🇷 韩国智能`[]🇹🇼 台湾智能`[]🚀 节点选择`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📱 TikTok`select`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🚀 手动切换
custom_proxy_group=💬 OpenAi`select`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇰🇷 韩国智能`[]🇹🇼 台湾智能`[]🇹🇷 土耳其智能`[]🚀 手动切换
custom_proxy_group=💬 Gemini`select`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇰🇷 韩国智能`[]🇹🇼 台湾智能`[]🇹🇷 土耳其智能`[]🚀 手动切换
custom_proxy_group=💬 其它Ai`select`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇰🇷 韩国智能`[]🇹🇼 台湾智能`[]🇹🇷 土耳其智能`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动智能`[]🚀 SELF节点`[]🇺🇸 美国智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇰🇷 韩国智能`[]🇹🇼 台湾智能`[]🇹🇷 土耳其智能`.*
custom_proxy_group=🚀 SELF节点`smart`(SELF|自建)`http://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇭🇰 香港智能`smart`(港|HK|hk|Hong Kong|HongKong|hongkong|深港)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇺🇸 美国智能`smart`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇯🇵 日本智能`smart`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|🇯🇵)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇸🇬 狮城智能`smart`(新加坡|坡|狮城|SG|Singapore)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇹🇼 台湾智能`smart`(台|新北|彰化|TW|Taiwan)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇰🇷 韩国智能`smart`(KR|Korea|KOR|首尔|韩|韓)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇨🇦 加拿大智能`smart`(加拿大|Canada|渥太华|温哥华|卡尔加里)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇬🇧 英国智能`smart`(英国|Britain|United Kingdom|England|伦敦)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇫🇷 法国智能`smart`(法国|France|巴黎)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇩🇪 德国智能`smart`(德国|Germany|柏林|法兰克福)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇳🇱 荷兰智能`smart`(荷兰|Netherlands|阿姆斯特丹)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🇹🇷 土耳其智能`smart`(土耳其|Turkey|Türkiye)`https://www.gstatic.com/generate_204`300`uselightgbm=true`collectdata=false`strategy=sticky-sessions`policy-priority=""
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动智能
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动智能`[]🚀 SELF节点`[]🇭🇰 香港智能`[]🇹🇼 台湾智能`[]🇸🇬 狮城智能`[]🇯🇵 日本智能`[]🇺🇸 美国智能`[]🇰🇷 韩国智能`[]🇹🇷 土耳其智能`[]🚀 手动切换`.*
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
